language: php
php:
- 7.0
script:
- php -l *.php
branches:
  only:
  - "/\\d\\.\\d\\.\\d/"
deploy:
  skip_cleanup: true
  provider: script
  script: deploy/deploy.sh
  on:
    tags: true
env:
  global:
  - SVN_REPOSITORY=https://plugins.svn.wordpress.org/cleverpush
  - secure: ODmmSfERGF6sMfjihqEfm+U9ps7z5IWWxrvnNY9ZoD0Kx9eq22eTWHrpRLhBYNRJByWdoRSaSHeXIg/yonkCBRbh+5+EQ2JNEI1om5Meo0Q/zJMzb75IriwzAhjz5JZuTGHR/+4lIPFLwXFUlaEml78G12FU1eAq1WdiALrqcry/EFDtk5HMQBbo4gsU5akMbD1unl6Ybqy6cwIsA79r31e+cVIXrq25UqS8hnU0vCdBC1efbuqJZjoWfbnHZ22DHVibUf1tj1t/MZqjn8hCizMm0avDWxApS5xH6S/8v6mfTmSMF8UpapqBYvXwXbYwnwaVek8/pWfPOlW6SSXlB6w3d5+kZELWkxOIN84HMUzFdbyfOO3qLb2SVx4mkegt++7Le7/BT0EBYioTCsgnOp2sWEDxqtNHE/iRIb8h2teN5PVDyVGvqNndC5o6DL3lAHJKmCDSzIob9Cvz7L8KZjDeTBDBgMsd0gy3laq+0kDWgm1iEsChrz+yVJ4OGK0YBBsivk1s8nNNCbykKHDeP8TytsPu8FA9dfRpkdw17CZREtTUG0UhruGTJZlJGTKOyiGY0tlS98bUj7r9AFqyz4EX0v9zbvh+61BnC7YrfqF12C1yqqWgPMO9o8IOviT7mztPaNbQW7NlRXDy0ucxEPQAo50c1FxEqoyh8ezxjg4=
  - secure: OxfJ2xE6PbVHmmH+oYd5JeAu/N8Cd2xcAnrnDsRKdUnB0SRNgLircCy6wPWTPZd3n0zG5bTtw5IWAyRUP5eCu3MiGdh9w4jlAkNYu5zPi48rzNFyj+lYVzIJY1D1zlvK53hIDBrklYRXSCmElRimSIqeBXzjS1nxIGfEj6svj+dr2b10o4f3fU2RedQy18KAC4qy/wESWV7DUxTIzPlPMxjUCjZJCFu3h6UgP1rG4VXCRgIfm+7tdzBzGUZWblQygKteJ9T4UsMNqsl1KpX3sIV0prs0FveKSMlaJZ1CH9nMVxhXfMjvML9xwX/AX+JAQWBFgyBmMhnWPBh2FBH2fHDn50AGFesXW6b5IA4TvGErMo1B5dRu8xYKBkQJHjEJRkBmQrcsw4lWwps/qQAr5GHrTAOwoNmn5GDoj0uyb1Lka3OwMJsfjS2MbLJsBsHk1UphxL6Mi30C9HSSqrr9Lsk0NjwhvmkPbvuXV4GGTlHFmrn3tmrGW7F/IQPBEHX+lU1NoMkan+g2aINx+dz4JfRl0vS2ytYRzZ7b0JYwWTvSIQQ/frcClG3LYVmpAiTlFiWYPOZ8Y6KSQMsuU5xZrj02niKzijjh6rO+/9N4HhLw2QJPCfnjXy4LHqaZtwym57ovaldAhQfxxA1L4MQVIQ7qqTH8fiY/uG0/aUtWG8g=
